baseURL = 'https://debiplobi.github.io'
locale = 'en-us'
title = 'blog'
theme = 'dead-simple'

[params.search]
enabled = false

[sitemap]
disable = false
filename = 'sitemap.xml'
priority = -1

[caches]
  [caches.images]
    dir = ':cacheDir/images'
